#!/bin/sh

# script/setup: This build the app and then deploys it.

set -e

cd "$(dirname "$0")/.."

script/setup
script/build

# deployment instructions here
HOST=cfruhr@musca.uberspace.de
DESTINATION_PATH=/var/www/virtual/cfruhr/blitzerkarte.openruhr.de/

ssh -o StrictHostKeyChecking=no $HOST mkdir -p $DESTINATION_PATH
rsync --progress --exclude-from '.deployignore' -avce "ssh -o StrictHostKeyChecking=no" ./ $HOST:$DESTINATION_PATH

echo "==> App is deployed!"
